services:
  - type: web
    name: scraping-notion-register
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python3 discord_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
